import type { SeoPageImagesMap } from '@/lib/seo/types';

export const SEO_PAGE_IMAGES: SeoPageImagesMap = {
  'caixa-engradado-madeira': [
    {
      filename: 'engradado-reforcado.webp',
      alt: 'engradado reforcado para caixa engradado de madeira',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado reforcado aplicada a caixa engradado de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'engradado-resistente.webp',
      alt: 'engradado resistente para caixa engradado de madeira',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado resistente aplicada a caixa engradado de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'engradado-leve.webp',
      alt: 'engradado leve para caixa engradado de madeira',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado leve aplicada a caixa engradado de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-exportacao': [
    {
      filename: 'madeira-fumigada-exportacao.png',
      alt: 'madeira fumigada exportacao para caixa para exportação',
      width: 500,
      height: 350,
      caption: 'Imagem de madeira fumigada exportacao aplicada a caixa para exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'mapamundi-min.webp',
      alt: 'mapamundi min para caixa para exportação',
      width: 2957,
      height: 1662,
      caption: 'Imagem de mapamundi min aplicada a caixa para exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'worldwide-min.webp',
      alt: 'worldwide min para caixa para exportação',
      width: 1217,
      height: 377,
      caption: 'Imagem de worldwide min aplicada a caixa para exportação.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-compensado': [
    {
      filename: 'caixa-economica.webp',
      alt: 'caixa economica para caixa de madeira compensado',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa economica aplicada a caixa de madeira compensado.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-estruturada.webp',
      alt: 'caixa estruturada para caixa de madeira compensado',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa estruturada aplicada a caixa de madeira compensado.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-leve.webp',
      alt: 'caixa leve para caixa de madeira compensado',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa leve aplicada a caixa de madeira compensado.',
      insertAfterBlock: 2,
    },
  ],
  'caixa-madeira-embalagem': [
    {
      filename: 'caixa-madeira-fumigada-3.webp',
      alt: 'caixa madeira fumigada 3 para caixa de madeira embalagem',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 3 aplicada a caixa de madeira embalagem.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa_madeira_fumigada_02.webp',
      alt: 'caixa madeira fumigada 02 para caixa de madeira embalagem',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 02 aplicada a caixa de madeira embalagem.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixas.webp',
      alt: 'caixas para caixa de madeira embalagem',
      width: 719,
      height: 260,
      caption: 'Imagem de caixas aplicada a caixa de madeira embalagem.',
      insertAfterBlock: 2,
    },
  ],
  'caixa-madeira-exportacao': [
    {
      filename: 'caixa-resistente.webp',
      alt: 'caixa resistente para caixa de madeira para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa resistente aplicada a caixa de madeira para exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-super-leve.webp',
      alt: 'caixa super leve para caixa de madeira para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super leve aplicada a caixa de madeira para exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-super-reforcada.webp',
      alt: 'caixa super reforcada para caixa de madeira para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super reforcada aplicada a caixa de madeira para exportação.',
      insertAfterBlock: 2,
    },
  ],
  'caixa-madeira-fumigada-exportacao': [
    {
      filename: 'caixa-madeira-fumigada-1.webp',
      alt: 'caixa madeira fumigada 1 para caixa de madeira fumigada para exportação',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 1 aplicada a caixa de madeira fumigada para exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-madeira-fumigada-2.webp',
      alt: 'caixa madeira fumigada 2 para caixa de madeira fumigada para exportação',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 2 aplicada a caixa de madeira fumigada para exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-madeira-fumigada-3.webp',
      alt: 'caixa madeira fumigada 3 para caixa de madeira fumigada para exportação',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 3 aplicada a caixa de madeira fumigada para exportação.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-fumigada': [
    {
      filename: 'caixa_madeira_fumigada_02.webp',
      alt: 'caixa madeira fumigada 02 para caixa de madeira fumigada',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 02 aplicada a caixa de madeira fumigada.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixas.webp',
      alt: 'caixas para caixa de madeira fumigada',
      width: 719,
      height: 260,
      caption: 'Imagem de caixas aplicada a caixa de madeira fumigada.',
      insertAfterBlock: 1,
    },
    {
      filename: 'header_caixas.webp',
      alt: 'header caixas para caixa de madeira fumigada',
      width: 1260,
      height: 240,
      caption: 'Imagem de header caixas aplicada a caixa de madeira fumigada.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-industrial': [
    {
      filename: 'fabrica-embalagens-madeira-2.webp',
      alt: 'fabrica embalagens madeira 2 para caixa de madeira industrial',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 2 aplicada a caixa de madeira industrial.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabrica-embalagens-madeira-3.webp',
      alt: 'fabrica embalagens madeira 3 para caixa de madeira industrial',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 3 aplicada a caixa de madeira industrial.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabricante-embalagem-madeira-1.webp',
      alt: 'fabricante embalagem madeira 1 para caixa de madeira industrial',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 1 aplicada a caixa de madeira industrial.',
      insertAfterBlock: 0,
    },
  ],
  'caixa-madeira-maquina-costura': [
    {
      filename: 'fabricante-embalagem-madeira-2.webp',
      alt: 'fabricante embalagem madeira 2 para caixa de madeira para máquina de costura',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 2 aplicada a caixa de madeira para máquina de costura.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabricante-embalagem-madeira-3.webp',
      alt: 'fabricante embalagem madeira 3 para caixa de madeira para máquina de costura',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 3 aplicada a caixa de madeira para máquina de costura.',
      insertAfterBlock: 1,
    },
    {
      filename: 'ribermax_fabrica.png',
      alt: 'ribermax fabrica para caixa de madeira para máquina de costura',
      width: 800,
      height: 500,
      caption: 'Imagem de ribermax fabrica aplicada a caixa de madeira para máquina de costura.',
      insertAfterBlock: 2,
    },
  ],
  'caixa-madeira-medida': [
    {
      filename: '20160127_161138-min.webp',
      alt: '20160127 161138 min para caixa de madeira sob medida',
      width: 400,
      height: 300,
      caption: 'Imagem de 20160127 161138 min aplicada a caixa de madeira sob medida.',
      insertAfterBlock: 0,
    },
    {
      filename: 'desenhista-tecnico-cotas.webp',
      alt: 'desenhista tecnico cotas para caixa de madeira sob medida',
      width: 1920,
      height: 1280,
      caption: 'Imagem de desenhista tecnico cotas aplicada a caixa de madeira sob medida.',
      insertAfterBlock: 1,
    },
    {
      filename: 'lupaCx.webp',
      alt: 'lupaCx para caixa de madeira sob medida',
      width: 256,
      height: 256,
      caption: 'Imagem de lupaCx aplicada a caixa de madeira sob medida.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-reforcada-transporte': [
    {
      filename: 'engradado-madeira-transporte-3.webp',
      alt: 'engradado madeira transporte 3 para caixa de madeira reforçada para transporte',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 3 aplicada a caixa de madeira reforçada para transporte.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-economica.webp',
      alt: 'caixa economica para caixa de madeira reforçada para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa economica aplicada a caixa de madeira reforçada para transporte.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-estruturada.webp',
      alt: 'caixa estruturada para caixa de madeira reforçada para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa estruturada aplicada a caixa de madeira reforçada para transporte.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-reforcada': [
    {
      filename: 'caixa-super-reforcada.webp',
      alt: 'caixa super reforcada para caixa de madeira reforçada',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super reforcada aplicada a caixa de madeira reforçada.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-madeira-fumigada-1.webp',
      alt: 'caixa madeira fumigada 1 para caixa de madeira reforçada',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 1 aplicada a caixa de madeira reforçada.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-madeira-fumigada-2.webp',
      alt: 'caixa madeira fumigada 2 para caixa de madeira reforçada',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 2 aplicada a caixa de madeira reforçada.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-tipo-exportacao': [
    {
      filename: 'caixa-reforcada.webp',
      alt: 'caixa reforcada para caixa de madeira tipo exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa reforcada aplicada a caixa de madeira tipo exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-resistente.webp',
      alt: 'caixa resistente para caixa de madeira tipo exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa resistente aplicada a caixa de madeira tipo exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-super-leve.webp',
      alt: 'caixa super leve para caixa de madeira tipo exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super leve aplicada a caixa de madeira tipo exportação.',
      insertAfterBlock: 1,
    },
  ],
  'caixa-madeira-transporte-preco': [
    {
      filename: 'caixa-madeira-fumigada-2.webp',
      alt: 'caixa madeira fumigada 2 para caixa de madeira para transporte preço',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 2 aplicada a caixa de madeira para transporte preço.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-madeira-fumigada-3.webp',
      alt: 'caixa madeira fumigada 3 para caixa de madeira para transporte preço',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 3 aplicada a caixa de madeira para transporte preço.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa_madeira_fumigada_02.webp',
      alt: 'caixa madeira fumigada 02 para caixa de madeira para transporte preço',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 02 aplicada a caixa de madeira para transporte preço.',
      insertAfterBlock: 2,
    },
  ],
  'caixa-madeira-transporte': [
    {
      filename: 'caixas.webp',
      alt: 'caixas para caixa de madeira para transporte',
      width: 719,
      height: 260,
      caption: 'Imagem de caixas aplicada a caixa de madeira para transporte.',
      insertAfterBlock: 0,
    },
    {
      filename: 'header_caixas.webp',
      alt: 'header caixas para caixa de madeira para transporte',
      width: 1260,
      height: 240,
      caption: 'Imagem de header caixas aplicada a caixa de madeira para transporte.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caminhao-min.webp',
      alt: 'caminhao min para caixa de madeira para transporte',
      width: 1800,
      height: 1196,
      caption: 'Imagem de caminhao min aplicada a caixa de madeira para transporte.',
      insertAfterBlock: 2,
    },
  ],
  'caixas-madeira-equipamentos': [
    {
      filename: 'caixa-madeira-fumigada-3.webp',
      alt: 'caixa madeira fumigada 3 para caixas de madeira para equipamentos',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 3 aplicada a caixas de madeira para equipamentos.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa_madeira_fumigada_02.webp',
      alt: 'caixa madeira fumigada 02 para caixas de madeira para equipamentos',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 02 aplicada a caixas de madeira para equipamentos.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixas.webp',
      alt: 'caixas para caixas de madeira para equipamentos',
      width: 719,
      height: 260,
      caption: 'Imagem de caixas aplicada a caixas de madeira para equipamentos.',
      insertAfterBlock: 1,
    },
  ],
  'caixas-madeira-industria': [
    {
      filename: 'header_caixas.webp',
      alt: 'header caixas para caixas de madeira para indústria',
      width: 1260,
      height: 240,
      caption: 'Imagem de header caixas aplicada a caixas de madeira para indústria.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabrica-embalagens-madeira-1.webp',
      alt: 'fabrica embalagens madeira 1 para caixas de madeira para indústria',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 1 aplicada a caixas de madeira para indústria.',
      insertAfterBlock: 1,
    },
    {
      filename: 'fabrica-embalagens-madeira-2.webp',
      alt: 'fabrica embalagens madeira 2 para caixas de madeira para indústria',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 2 aplicada a caixas de madeira para indústria.',
      insertAfterBlock: 1,
    },
  ],
  'caixas-madeira-maquinas': [
    {
      filename: 'fabrica-embalagens-madeira-3.webp',
      alt: 'fabrica embalagens madeira 3 para caixas de madeira para máquinas',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 3 aplicada a caixas de madeira para máquinas.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabricante-embalagem-madeira-1.webp',
      alt: 'fabricante embalagem madeira 1 para caixas de madeira para máquinas',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 1 aplicada a caixas de madeira para máquinas.',
      insertAfterBlock: 1,
    },
    {
      filename: 'fabricante-embalagem-madeira-2.webp',
      alt: 'fabricante embalagem madeira 2 para caixas de madeira para máquinas',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 2 aplicada a caixas de madeira para máquinas.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-exportacao-maquinas': [
    {
      filename: 'mapamundi-min.webp',
      alt: 'mapamundi min para embalagem para exportação de máquinas',
      width: 2957,
      height: 1662,
      caption: 'Imagem de mapamundi min aplicada a embalagem para exportação de máquinas.',
      insertAfterBlock: 0,
    },
    {
      filename: 'worldwide-min.webp',
      alt: 'worldwide min para embalagem para exportação de máquinas',
      width: 1217,
      height: 377,
      caption: 'Imagem de worldwide min aplicada a embalagem para exportação de máquinas.',
      insertAfterBlock: 1,
    },
    {
      filename: 'worldwide.webp',
      alt: 'worldwide para embalagem para exportação de máquinas',
      width: 426,
      height: 132,
      caption: 'Imagem de worldwide aplicada a embalagem para exportação de máquinas.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-fumigada': [
    {
      filename: 'porto-de-santos-optimized.avif',
      alt: 'porto de santos optimized para embalagem fumigada',
      width: 1500,
      height: 1000,
      caption: 'Imagem de porto de santos optimized aplicada a embalagem fumigada.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-economica.webp',
      alt: 'caixa economica para embalagem fumigada',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa economica aplicada a embalagem fumigada.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-estruturada.webp',
      alt: 'caixa estruturada para embalagem fumigada',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa estruturada aplicada a embalagem fumigada.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-madeira-equipamentos': [
    {
      filename: 'caixas-madeira-equipamentos-3.webp',
      alt: 'caixas madeira equipamentos 3 para embalagem de madeira para equipamentos',
      width: 400,
      height: 300,
      caption: 'Imagem de caixas madeira equipamentos 3 aplicada a embalagem de madeira para equipamentos.',
      insertAfterBlock: 0,
    },
    {
      filename: 'diversity/caixa-madeira-compensado.png',
      alt: 'caixa madeira compensado para embalagem de madeira para equipamentos',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira compensado aplicada a embalagem de madeira para equipamentos.',
      insertAfterBlock: 1,
    },
    {
      filename: 'diversity/caixas-madeira-equipamentos.png',
      alt: 'caixas madeira equipamentos para embalagem de madeira para equipamentos',
      width: 400,
      height: 300,
      caption: 'Imagem de caixas madeira equipamentos aplicada a embalagem de madeira para equipamentos.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-madeira-exportacao': [
    {
      filename: 'caixa-super-leve.webp',
      alt: 'caixa super leve para embalagem de madeira exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super leve aplicada a embalagem de madeira exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-super-reforcada.webp',
      alt: 'caixa super reforcada para embalagem de madeira exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super reforcada aplicada a embalagem de madeira exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-madeira-fumigada-1.webp',
      alt: 'caixa madeira fumigada 1 para embalagem de madeira exportação',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 1 aplicada a embalagem de madeira exportação.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-madeira-fumigada': [
    {
      filename: 'caixa-madeira-fumigada-2.webp',
      alt: 'caixa madeira fumigada 2 para embalagem de madeira fumigada',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 2 aplicada a embalagem de madeira fumigada.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-madeira-fumigada-3.webp',
      alt: 'caixa madeira fumigada 3 para embalagem de madeira fumigada',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 3 aplicada a embalagem de madeira fumigada.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa_madeira_fumigada_02.webp',
      alt: 'caixa madeira fumigada 02 para embalagem de madeira fumigada',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 02 aplicada a embalagem de madeira fumigada.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-madeira-maquinas': [
    {
      filename: 'caixa-resistente.webp',
      alt: 'caixa resistente para embalagem de madeira para maquinas',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa resistente aplicada a embalagem de madeira para maquinas.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-super-leve.webp',
      alt: 'caixa super leve para embalagem de madeira para maquinas',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super leve aplicada a embalagem de madeira para maquinas.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-super-reforcada.webp',
      alt: 'caixa super reforcada para embalagem de madeira para maquinas',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super reforcada aplicada a embalagem de madeira para maquinas.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-madeira-transporte': [
    {
      filename: 'engradado-leve.webp',
      alt: 'engradado leve para embalagem de madeira para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado leve aplicada a embalagem de madeira para transporte.',
      insertAfterBlock: 0,
    },
    {
      filename: 'engradado_economico-300x273.webp',
      alt: 'engradado economico 300x273 para embalagem de madeira para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado economico 300x273 aplicada a embalagem de madeira para transporte.',
      insertAfterBlock: 1,
    },
    {
      filename: 'engradado-madeira-transporte-3.webp',
      alt: 'engradado madeira transporte 3 para embalagem de madeira para transporte',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 3 aplicada a embalagem de madeira para transporte.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-padrao-exportacao': [
    {
      filename: 'fumigacao.webp',
      alt: 'fumigacao para embalagem padrão exportação',
      width: 155,
      height: 79,
      caption: 'Imagem de fumigacao aplicada a embalagem padrão exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'certificacao_min.webp',
      alt: 'certificacao min para embalagem padrão exportação',
      width: 225,
      height: 225,
      caption: 'Imagem de certificacao min aplicada a embalagem padrão exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'IPPC.webp',
      alt: 'IPPC para embalagem padrão exportação',
      width: 333,
      height: 152,
      caption: 'Imagem de IPPC aplicada a embalagem padrão exportação.',
      insertAfterBlock: 1,
    },
  ],
  'embalagem-tipo-exportacao': [
    {
      filename: 'madeira-fumigada-exportacao.png',
      alt: 'madeira fumigada exportacao para embalagem tipo exportação',
      width: 500,
      height: 350,
      caption: 'Imagem de madeira fumigada exportacao aplicada a embalagem tipo exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'mapamundi-min.webp',
      alt: 'mapamundi min para embalagem tipo exportação',
      width: 2957,
      height: 1662,
      caption: 'Imagem de mapamundi min aplicada a embalagem tipo exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'worldwide-min.webp',
      alt: 'worldwide min para embalagem tipo exportação',
      width: 1217,
      height: 377,
      caption: 'Imagem de worldwide min aplicada a embalagem tipo exportação.',
      insertAfterBlock: 1,
    },
  ],
  'embalagens-especiais-madeira': [
    {
      filename: '20160127_161138-min.webp',
      alt: '20160127 161138 min para embalagens especiais de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de 20160127 161138 min aplicada a embalagens especiais de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fumigacao.webp',
      alt: 'fumigacao para embalagens especiais de madeira',
      width: 155,
      height: 79,
      caption: 'Imagem de fumigacao aplicada a embalagens especiais de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'certificacao_min.webp',
      alt: 'certificacao min para embalagens especiais de madeira',
      width: 225,
      height: 225,
      caption: 'Imagem de certificacao min aplicada a embalagens especiais de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'embalagens-exportacao': [
    {
      filename: 'caixa-estruturada.webp',
      alt: 'caixa estruturada para embalagens para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa estruturada aplicada a embalagens para exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-leve.webp',
      alt: 'caixa leve para embalagens para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa leve aplicada a embalagens para exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-reforcada.webp',
      alt: 'caixa reforcada para embalagens para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa reforcada aplicada a embalagens para exportação.',
      insertAfterBlock: 1,
    },
  ],
  'embalagens-industriais-madeira': [
    {
      filename: 'caixas-madeira-equipamentos-1.webp',
      alt: 'caixas madeira equipamentos 1 para embalagens industriais de madeira',
      width: 400,
      height: 225,
      caption: 'Imagem de caixas madeira equipamentos 1 aplicada a embalagens industriais de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixas-madeira-equipamentos-2.webp',
      alt: 'caixas madeira equipamentos 2 para embalagens industriais de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de caixas madeira equipamentos 2 aplicada a embalagens industriais de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixas-madeira-equipamentos-3.webp',
      alt: 'caixas madeira equipamentos 3 para embalagens industriais de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de caixas madeira equipamentos 3 aplicada a embalagens industriais de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'embalagens-madeira-medida': [
    {
      filename: 'caixa-economica.webp',
      alt: 'caixa economica para embalagens de madeira sob medida',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa economica aplicada a embalagens de madeira sob medida.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-estruturada.webp',
      alt: 'caixa estruturada para embalagens de madeira sob medida',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa estruturada aplicada a embalagens de madeira sob medida.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-leve.webp',
      alt: 'caixa leve para embalagens de madeira sob medida',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa leve aplicada a embalagens de madeira sob medida.',
      insertAfterBlock: 1,
    },
  ],
  'embalagens-madeira-ribeirao-preto': [
    {
      filename: 'empresa.webp',
      alt: 'empresa para embalagens de madeira em ribeirão preto',
      width: 956,
      height: 538,
      caption: 'Imagem de empresa aplicada a embalagens de madeira em ribeirão preto.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabrica-embalagens-madeira-2.webp',
      alt: 'fabrica embalagens madeira 2 para embalagens de madeira em ribeirão preto',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 2 aplicada a embalagens de madeira em ribeirão preto.',
      insertAfterBlock: 1,
    },
    {
      filename: 'fabrica-embalagens-madeira-1.webp',
      alt: 'fabrica embalagens madeira 1 para embalagens de madeira em ribeirão preto',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 1 aplicada a embalagens de madeira em ribeirão preto.',
      insertAfterBlock: 1,
    },
  ],
  'embalagens-madeira': [
    {
      filename: 'caixa-super-reforcada.webp',
      alt: 'caixa super reforcada para embalagens de madeira',
      width: 300,
      height: 273,
      caption: 'Imagem de caixa super reforcada aplicada a embalagens de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caixa-madeira-fumigada-1.webp',
      alt: 'caixa madeira fumigada 1 para embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 1 aplicada a embalagens de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caixa-madeira-fumigada-2.webp',
      alt: 'caixa madeira fumigada 2 para embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de caixa madeira fumigada 2 aplicada a embalagens de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'empresa-caixas-madeira': [
    {
      filename: 'empresa.webp',
      alt: 'empresa para empresa de caixas de madeira',
      width: 956,
      height: 538,
      caption: 'Imagem de empresa aplicada a empresa de caixas de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: '20160127_161138-min.webp',
      alt: '20160127 161138 min para empresa de caixas de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de 20160127 161138 min aplicada a empresa de caixas de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'IMG_20190902_165552685-min.webp',
      alt: 'IMG 20190902 165552685 min para empresa de caixas de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de IMG 20190902 165552685 min aplicada a empresa de caixas de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'empresa-embalagens-madeira': [
    {
      filename: 'IMG_20201015_165641469-min.webp',
      alt: 'IMG 20201015 165641469 min para empresa de embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de IMG 20201015 165641469 min aplicada a empresa de embalagens de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'IMG_20201016_122913136_HDR-min.webp',
      alt: 'IMG 20201016 122913136 HDR min para empresa de embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de IMG 20201016 122913136 HDR min aplicada a empresa de embalagens de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'IMG_20201208_173244057-min.webp',
      alt: 'IMG 20201208 173244057 min para empresa de embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de IMG 20201208 173244057 min aplicada a empresa de embalagens de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-exportacao': [
    {
      filename: 'engradado_economico-300x273.webp',
      alt: 'engradado economico 300x273 para engradado para exportação',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado economico 300x273 aplicada a engradado para exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'engradado-madeira-transporte-1.webp',
      alt: 'engradado madeira transporte 1 para engradado para exportação',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 1 aplicada a engradado para exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'engradado-madeira-transporte-2.webp',
      alt: 'engradado madeira transporte 2 para engradado para exportação',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 2 aplicada a engradado para exportação.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-madeira-comprar': [
    {
      filename: 'engradado-madeira-transporte-3.webp',
      alt: 'engradado madeira transporte 3 para engradado de madeira comprar',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 3 aplicada a engradado de madeira comprar.',
      insertAfterBlock: 0,
    },
    {
      filename: 'caminhao-min.webp',
      alt: 'caminhao min para engradado de madeira comprar',
      width: 1800,
      height: 1196,
      caption: 'Imagem de caminhao min aplicada a engradado de madeira comprar.',
      insertAfterBlock: 1,
    },
    {
      filename: 'caminhao_novo.png',
      alt: 'caminhao novo para engradado de madeira comprar',
      width: 1024,
      height: 495,
      caption: 'Imagem de caminhao novo aplicada a engradado de madeira comprar.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-madeira-equipamentos': [
    {
      filename: 'fumigacao.webp',
      alt: 'fumigacao para engradado de madeira para equipamentos',
      width: 155,
      height: 79,
      caption: 'Imagem de fumigacao aplicada a engradado de madeira para equipamentos.',
      insertAfterBlock: 0,
    },
    {
      filename: 'certificacao_min.webp',
      alt: 'certificacao min para engradado de madeira para equipamentos',
      width: 225,
      height: 225,
      caption: 'Imagem de certificacao min aplicada a engradado de madeira para equipamentos.',
      insertAfterBlock: 1,
    },
    {
      filename: 'IPPC.webp',
      alt: 'IPPC para engradado de madeira para equipamentos',
      width: 333,
      height: 152,
      caption: 'Imagem de IPPC aplicada a engradado de madeira para equipamentos.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-madeira-exportacao': [
    {
      filename: 'madeira-fumigada-exportacao.png',
      alt: 'madeira fumigada exportacao para engradado de madeira para exportação',
      width: 500,
      height: 350,
      caption: 'Imagem de madeira fumigada exportacao aplicada a engradado de madeira para exportação.',
      insertAfterBlock: 0,
    },
    {
      filename: 'mapamundi-min.webp',
      alt: 'mapamundi min para engradado de madeira para exportação',
      width: 2957,
      height: 1662,
      caption: 'Imagem de mapamundi min aplicada a engradado de madeira para exportação.',
      insertAfterBlock: 1,
    },
    {
      filename: 'worldwide-min.webp',
      alt: 'worldwide min para engradado de madeira para exportação',
      width: 1217,
      height: 377,
      caption: 'Imagem de worldwide min aplicada a engradado de madeira para exportação.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-madeira-maquinas': [
    {
      filename: 'worldwide.webp',
      alt: 'worldwide para engradado de madeira para máquinas',
      width: 426,
      height: 132,
      caption: 'Imagem de worldwide aplicada a engradado de madeira para máquinas.',
      insertAfterBlock: 0,
    },
    {
      filename: 'porto-de-santos-optimized.avif',
      alt: 'porto de santos optimized para engradado de madeira para máquinas',
      width: 1500,
      height: 1000,
      caption: 'Imagem de porto de santos optimized aplicada a engradado de madeira para máquinas.',
      insertAfterBlock: 1,
    },
    {
      filename: 'engradado-reforcado.webp',
      alt: 'engradado reforcado para engradado de madeira para máquinas',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado reforcado aplicada a engradado de madeira para máquinas.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-madeira-transporte': [
    {
      filename: 'engradado-resistente.webp',
      alt: 'engradado resistente para engradado de madeira para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado resistente aplicada a engradado de madeira para transporte.',
      insertAfterBlock: 0,
    },
    {
      filename: 'engradado-leve.webp',
      alt: 'engradado leve para engradado de madeira para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado leve aplicada a engradado de madeira para transporte.',
      insertAfterBlock: 1,
    },
    {
      filename: 'engradado_economico-300x273.webp',
      alt: 'engradado economico 300x273 para engradado de madeira para transporte',
      width: 300,
      height: 273,
      caption: 'Imagem de engradado economico 300x273 aplicada a engradado de madeira para transporte.',
      insertAfterBlock: 1,
    },
  ],
  'engradado-madeira': [
    {
      filename: 'engradado-madeira-transporte-1.webp',
      alt: 'engradado madeira transporte 1 para engradado de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 1 aplicada a engradado de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'engradado-madeira-transporte-2.webp',
      alt: 'engradado madeira transporte 2 para engradado de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 2 aplicada a engradado de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'engradado-madeira-transporte-3.webp',
      alt: 'engradado madeira transporte 3 para engradado de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de engradado madeira transporte 3 aplicada a engradado de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fabrica-caixas-madeira': [
    {
      filename: 'IMG_20201016_122913136_HDR-min.webp',
      alt: 'IMG 20201016 122913136 HDR min para fábrica de caixas de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de IMG 20201016 122913136 HDR min aplicada a fábrica de caixas de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'IMG_20201208_173244057-min.webp',
      alt: 'IMG 20201208 173244057 min para fábrica de caixas de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de IMG 20201208 173244057 min aplicada a fábrica de caixas de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'm_IMG_20201208_173926536-min.webp',
      alt: 'm IMG 20201208 173926536 min para fábrica de caixas de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de m IMG 20201208 173926536 min aplicada a fábrica de caixas de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fabrica-embalagens-madeira': [
    {
      filename: 'm_IMG_20201210_102658269-min.webp',
      alt: 'm IMG 20201210 102658269 min para fábrica de embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de m IMG 20201210 102658269 min aplicada a fábrica de embalagens de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'm_IMG_20210115_110017071-min.webp',
      alt: 'm IMG 20210115 110017071 min para fábrica de embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de m IMG 20210115 110017071 min aplicada a fábrica de embalagens de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'm_IMG_20210127_161914408-min.webp',
      alt: 'm IMG 20210127 161914408 min para fábrica de embalagens de madeira',
      width: 300,
      height: 400,
      caption: 'Imagem de m IMG 20210127 161914408 min aplicada a fábrica de embalagens de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fabricacao-caixas-madeira': [
    {
      filename: 'desenhista-tecnico-cotas.webp',
      alt: 'desenhista tecnico cotas para fabricação de caixas de madeira',
      width: 1920,
      height: 1280,
      caption: 'Imagem de desenhista tecnico cotas aplicada a fabricação de caixas de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'lupaCx.webp',
      alt: 'lupaCx para fabricação de caixas de madeira',
      width: 256,
      height: 256,
      caption: 'Imagem de lupaCx aplicada a fabricação de caixas de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'madeira-vs-papelao.webp',
      alt: 'madeira vs papelao para fabricação de caixas de madeira',
      width: 350,
      height: 200,
      caption: 'Imagem de madeira vs papelao aplicada a fabricação de caixas de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fabricacao-embalagens-madeira': [
    {
      filename: 'madeira_Xpapelao.webp',
      alt: 'madeira Xpapelao para fabricação de embalagens de madeira',
      width: 350,
      height: 200,
      caption: 'Imagem de madeira Xpapelao aplicada a fabricação de embalagens de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'sarrafos_sob_medida-300x273.webp',
      alt: 'sarrafos sob medida 300x273 para fabricação de embalagens de madeira',
      width: 300,
      height: 273,
      caption: 'Imagem de sarrafos sob medida 300x273 aplicada a fabricação de embalagens de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'palete-sob-medida.webp',
      alt: 'palete sob medida para fabricação de embalagens de madeira',
      width: 300,
      height: 273,
      caption: 'Imagem de palete sob medida aplicada a fabricação de embalagens de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fabricante-embalagem-madeira': [
    {
      filename: 'fabrica-embalagens-madeira-1.webp',
      alt: 'fabrica embalagens madeira 1 para fabricante de embalagem de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 1 aplicada a fabricante de embalagem de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabrica-embalagens-madeira-2.webp',
      alt: 'fabrica embalagens madeira 2 para fabricante de embalagem de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 2 aplicada a fabricante de embalagem de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'fabrica-embalagens-madeira-3.webp',
      alt: 'fabrica embalagens madeira 3 para fabricante de embalagem de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de fabrica embalagens madeira 3 aplicada a fabricante de embalagem de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fornecedor-caixa-madeira': [
    {
      filename: 'fabricante-embalagem-madeira-1.webp',
      alt: 'fabricante embalagem madeira 1 para fornecedor de caixa de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 1 aplicada a fornecedor de caixa de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'fabricante-embalagem-madeira-2.webp',
      alt: 'fabricante embalagem madeira 2 para fornecedor de caixa de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 2 aplicada a fornecedor de caixa de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: 'fabricante-embalagem-madeira-3.webp',
      alt: 'fabricante embalagem madeira 3 para fornecedor de caixa de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de fabricante embalagem madeira 3 aplicada a fornecedor de caixa de madeira.',
      insertAfterBlock: 1,
    },
  ],
  'fornecedores-embalagens-madeira': [
    {
      filename: 'ribermax_fabrica.png',
      alt: 'ribermax fabrica para fornecedores de embalagens de madeira',
      width: 800,
      height: 500,
      caption: 'Imagem de ribermax fabrica aplicada a fornecedores de embalagens de madeira.',
      insertAfterBlock: 0,
    },
    {
      filename: 'empresa.webp',
      alt: 'empresa para fornecedores de embalagens de madeira',
      width: 956,
      height: 538,
      caption: 'Imagem de empresa aplicada a fornecedores de embalagens de madeira.',
      insertAfterBlock: 1,
    },
    {
      filename: '20160127_161138-min.webp',
      alt: '20160127 161138 min para fornecedores de embalagens de madeira',
      width: 400,
      height: 300,
      caption: 'Imagem de 20160127 161138 min aplicada a fornecedores de embalagens de madeira.',
      insertAfterBlock: 1,
    },
  ],
};
